---
name: build and publish
on:
  push:
    branches:
      - main
    paths:
      - 'Containerfile'
      - 'sudoers'
      - '.github/workflows/build-and-push.yaml'

jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Get Git short Hash
      run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Get TeamRedMiner version
      run: echo "TRM_REL=$(grep 'ENV' < ./Containerfile | sed -e 's#ENV TRM_VERSION\=##g' -e 's###g')" >> $GITHUB_ENV

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2.6.2
      with:
        image: teamredminer
        tags: ${{ env.SHORT_SHA }} latest ${{ env.TRM_REL }}
        oci: true
        layers: true
        dockerfiles:
          ./Containerfile
    
    - name: Push to GHCR
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2.3.2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags:  ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.actor }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_MINE }}

    - name: Use the image
      run: echo "New image has been pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"