
name: build and publish
on: push

jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Get Git short Hash
      run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2.5.1
      with:
        image: teamredminer
        tags: ${{ env.SHORT_SHA }} latest
        oci: true
        layers: true
        dockerfiles:
          ./Containerfile
    
    - name: Push to GHCR
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2.1.1
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags:  ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.actor }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT_MINE }}

    - name: Use the image
      run: echo "New image has been pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"